config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'chats/show'
  resources :chats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "chats#show"
  mount ActionCable.server => '/cable'
  resources :message
  resources :users do
    resources :rooms
  end
  
/   namespace :api, defaults: {format: :json} do
     namespace :v1 do
       resources :users
     end
   end  /
  get 'json_users', to: 'json#list_all_json'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :user
  has_many :user, through: :room
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    after_create_commit { ChatBroadcastJob.perform_later(self) }
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :chat_rooms	
  has_many :chat_rooms, through: :room	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  def appear
    self.online = true   
    self.save!
  end
  def disappear
   self.online = false
   self.save!
  end
  
  def online?
   if self.online
      "online"
   else
      "offline"
   end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?



    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(
        :sign_up, keys: %i[name]
      )
    end
    def self.render_with_signed_in_user(user, *args)
      ActionController::Renderer::RACK_KEY_TRANSLATION['warden'] ||= 'warden'
      proxy = Warden::Proxy.new({}, Warden::Manager.new({})).tap{|i| i.set_user(user, scope: :user) }
      renderer = self.renderer.new('warden' => proxy)
      renderer.render(*args)
    end
    private

    # Overwriting the sign_out redirect path method
/    def after_sign_out_path_for(resource_or_scope)

      root_path
    end
/
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :authenticate_user!
  def show
   @messages = Message.all
  end
  def create
  
  end
end

app/controllers/json_controller.rb
class JsonController < ApplicationController
    def list_all_json
     @users = User.all
     @us = []
     @users.each do |u|
      user = Hash.new
      user['id']=u.id
      user['name']=u.name
      user['online']=u.online
      user['current_user_id']=current_user.id
      @us.push(user)
     end 
     render json: @us
   end
 
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
    def destroy
     @msg = Message.find(params[:id])
     @user = @msg.secondary_user
     @msg.destroy

     redirect_to user_rooms_path(@user)    
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :authenticate_user!
    def create
    #    @chat_room = ChatRoom.create
    #    Room.create(user: current_user, chat_room: @chat_room)
    #    @room = Room.create(user: params['user'], chat_room: @chat_room)
        redirect_to  user_rooms_path
    end
    def index
	@chat_with_user = User.find params['user_id']
        @user = params['user_id']
        @messages = Message.where("user_id = ?
                                   and secondary_user = ?
                                   or user_id = ? 
                                   and secondary_user = ?", 
                                   current_user, 
                                   @user, 
                                   @user, 
                                   current_user).order(:id)
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
   def index
    @users = User.all
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def mostra_usuario_atual
       p current_user if user_signed_in?
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/show.html.erb
<div align="center" class="container">
  <h1 class="title">Para começar acesse a lista de usuários</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MyChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
   
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="current-user" id="<%= current_user.try(:id) %>">
  </head>

  <body>
      <div>
        <%=  "id: #{current_user.id}" if user_signed_in? %>
        <%= "Olá #{current_user.name}" if user_signed_in?%>
      </div>
       <%= link_to('Home', root_path) if user_signed_in?%>
       <%= link_to('Lista de usuários', users_path) if user_signed_in?%>
       <%= link_to('Logout', destroy_user_session_path, method:'delete', class: 'nav-link') if user_signed_in?%>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/messages/_messages.html.erb
<%p "*******************************************"%>
<%p current_user%>
<%p message.user.id%>
<%p "*******************************************"%>
<%p message.secondary_user%>
<%p message.user%>
<%p message%>
<div data-from-user-id="<%= message.user.id %>" class="message" data-user-id="<%= message.secondary_user %>">
   <p>
     <%= message.created_at.strftime("%d/%m/%y %H:%M ")%>
     <%= message.user.name %>:
     <%= message.content %>
     <%= link_to 'Remover', message_path(message), method: :delete if  message.user == current_user%> 
   </p>
 </div>

app/views/rooms/index.html.erb
<%= render "shared/room_messages" %>

app/views/shared/_comment.html.erb
<article data-user-id="<%= comment.user.id %>">
</article>

app/views/shared/_room_messages.html.erb
<div align="center" class="container">
  <input type="hidden" id="secondary_user_id" value="<%= @chat_with_user.id %>">
  <h1 class="title">Bate Papo com <%= @chat_with_user.name %> <%= @chat_with_user.online? %></h1>
<div name="data-chat-room-user-id" id="<%= @user %>" style="width: 80%; height: 300px; overflow-y: scroll;" >
  <div id="messages">

  <% @messages.each do |m| %>
   <div class="message">
    <p>
      <%= m.created_at.strftime("%d/%m/%y %H:%M ")%>
      <%= m.user.name %>:
      <%= m.content %>
      <%if current_user == m.user || current_user.admin%>
      <%= link_to 'Remover', message_path(m), method: :delete %>
      <% end %>
      </p>
   </div>
  <%end%>
  </div>
</div>
<div>
  <form>
    <input type="text" data-behavior="chat_speaker" placeholder=" Diga alguma coisa :) ">
  </form>
</div>

</div>

app/views/users/index.html.erb
<% javascript_include_tag 'users'%>
<div id="list-users">
<table style="width:10%">
<%@users.each do |user|%>
<div>
<tr>
  <td><%= link_to(user.name, user_rooms_path(user), method:'post') if user_signed_in? && current_user.name != user.name %></td>
  <td id='status-on-off-<%=user.id%>'>  <%=  user.online? if current_user.name != user.name   %></td>
</tr>

</div>
<%end%>
</table>
</div>